services:
  mongo:
    image: mongo:7
    container_name: sports-pot-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: sports-pot

volumes:
  mongo-data:
